// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUWkfhP9ISJhzhBsLv_Cz3Hzm07yeUtLQ',
    appId: '1:260466718218:web:e7f67f73e55a7246b111f3',
    messagingSenderId: '260466718218',
    projectId: 'introduction-resume',
    authDomain: 'introduction-resume.firebaseapp.com',
    storageBucket: 'introduction-resume.appspot.com',
    measurementId: 'G-F7SLFJVCVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7UQTi0KVKe0RUqgEgG-_LgJfycwk9A0I',
    appId: '1:260466718218:android:9443dda4a43a50f6b111f3',
    messagingSenderId: '260466718218',
    projectId: 'introduction-resume',
    storageBucket: 'introduction-resume.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6ZphRrzECyXRigUQENyxTKjPhKGh9WM',
    appId: '1:260466718218:ios:a71db7d7506ead8bb111f3',
    messagingSenderId: '260466718218',
    projectId: 'introduction-resume',
    storageBucket: 'introduction-resume.appspot.com',
    iosBundleId: 'com.example.introduction',
  );
}
